In [1]:
# Tensors are similar to numpy's ndarrays, with the addition being that
# Tensors can also be used on a GPU to accelerate computing

In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.Tensor(5, 3)
print(x)


 0.0000e+00  0.0000e+00  2.7566e+00
 4.5785e-41  2.6506e+00  4.5785e-41
 1.5294e-38  0.0000e+00  1.5294e-38
 0.0000e+00  3.7980e+05  4.5785e-41
 3.6782e+05  4.5785e-41  2.6550e+00
[torch.FloatTensor of size 5x3]



In [4]:
x = torch.rand(5, 3)
print(x)


 0.4943  0.3963  0.6092
 0.8286  0.8993  0.2210
 0.2653  0.1924  0.9760
 0.6293  0.6220  0.8629
 0.1286  0.7573  0.4992
[torch.FloatTensor of size 5x3]



In [5]:
print(x.size())

torch.Size([5, 3])


In [6]:
y = torch.rand(5, 3)
print(x + y)


 1.3150  0.7053  1.1128
 1.7810  1.1155  0.2501
 0.6782  0.6914  0.9861
 0.6584  1.5254  1.4475
 0.9236  1.1510  1.2213
[torch.FloatTensor of size 5x3]



In [9]:
y


 0.8207  0.3090  0.5037
 0.9524  0.2162  0.0291
 0.4129  0.4990  0.0101
 0.0291  0.9034  0.5846
 0.7950  0.3937  0.7221
[torch.FloatTensor of size 5x3]

In [7]:
print(torch.add(x, y))


 1.3150  0.7053  1.1128
 1.7810  1.1155  0.2501
 0.6782  0.6914  0.9861
 0.6584  1.5254  1.4475
 0.9236  1.1510  1.2213
[torch.FloatTensor of size 5x3]



In [8]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)
# make new tensor and give the result to the new tensor


 1.3150  0.7053  1.1128
 1.7810  1.1155  0.2501
 0.6782  0.6914  0.9861
 0.6584  1.5254  1.4475
 0.9236  1.1510  1.2213
[torch.FloatTensor of size 5x3]



In [10]:
y.add_(x)
print(y)
# adding '_' makes an operation to mutate a tensor in-place


 1.3150  0.7053  1.1128
 1.7810  1.1155  0.2501
 0.6782  0.6914  0.9861
 0.6584  1.5254  1.4475
 0.9236  1.1510  1.2213
[torch.FloatTensor of size 5x3]



In [13]:
print(y[:, 0])


 1.3150
 1.7810
 0.6782
 0.6584
 0.9236
[torch.FloatTensor of size 5]



In [14]:
# The torch Tensor and numpy array will share their underlying memory
# locations, and changing one will change the other

In [17]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [19]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [20]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [21]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [22]:
torch.cuda.is_available()

False